---
title: "ggplot2 et la grammaire graphique"
author: 
- Robin Cura
- Léa Christophe
date: last-modified
ordre: 03
code-fold: true
code-tools: true
format:
  html:
    theme: cosmo
    code-copy: true
    embed-resources: TRUE
  # pdf:
  #   toc: true
  #   number-sections: true
  #   colorlinks: true
  #   output-file: "import"
  #   output-ext:  "pdf"
---


::: {.callout-note}
Ce cours a été élaboré dans le cadre d'une [séance de formation](https://elementr.netlify.app/posts/seance4_ggplot) organisée par le groupe d'utilisateur·rices [**ElementR**](https://elementr.netlify.app/). 
:::

\

Cette séance s'adresse aussi bien aux débutant·e·s qu'aux intié·e·s. Elle a pour objectif de présenter le package [ggplot2](https://ggplot2.tidyverse.org/index.html). Ce package généraliste de représentation graphique, basé sur la [grammaire graphique](https://www.amazon.com/Grammar-Graphics-Statistics-Computing/dp/0387245448/ref=as_li_ss_tl) théorisée par Leland Wilkinson, est une référence dans la communauté R.

\

**Plan de séance :**

1.  Faire un graphique avec R
2.  La [grammaire graphique](https://www.amazon.com/Grammar-Graphics-Statistics-Computing/dp/0387245448/ref=as_li_ss_tl)\
3.  **ggplot2** : une implémentation de la grammar of graphics\
4.  Documentation & aide
5.  Atelier pratique !

## <i class="bi bi-book"></i> Support & exercice {.title}
 
<iframe class="slide2" src="https://elementr.gitpages.huma-num.fr/session_graphique/ggplot2/#/title-slide">

</iframe>

→ Consulter en [plein écran](https://elementr.gitpages.huma-num.fr/session_graphique/ggplot2/#/title-slide)\
→ Accéder au [code source](https://gitlab.huma-num.fr/elementr/session_graphique/ggplot2)\
<!-- → Télécharger en [pdf]()\ -->

\



**Données et scripts :**

<!-- Un projet Rstudio contenant des données et des scripts R (exercice et correction) utilisés durant la séance est téléchargeable ici : -->

Les exercices (scripts R, données et correction) et le support de cours sont mis à disposition sur un [dépôt GitLab](https://gitlab.huma-num.fr/elementr/session_graphique/ggplot2). Cliquez ci-dessous pour télécharger une archive du dépôt :

<center><a href="https://gitlab.huma-num.fr/elementr/session_graphique/ggplot2/-/raw/main/ElementR_ggplot.zip?inline=false" class="btn btn-success" role="button" aria-disabled="true"><i class="bi bi-cloud-arrow-down"></i> ElementR_ggplot.zip</a></center>

\

**Conditions d'utilisation :**

Le support utilisé pour cette séance est libre d'utilisation et d'adaptation (licence [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.fr)). Vous devez néanmoins créditer l'œuvre, indiquer les éventuelles modifications et utiliser les mêmes conditions de partage.

\

